import Image from "next/image";
import login_screen from "../../public/log_in_screen.png";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-authBG w-full h-[100vh] rounded-md flex justify-center items-center">
      <div className="flex w-[70vw] h-fit shadow-md rounded-md">
        <div className="w-3/5 bg-white rounded-l-md p-16 h-fit">{children}</div>
        <div className="bg-gradient-to-r from-authGradient1 to-authGradient2 w-2/5 rounded-r-md relative">
          <Image
            src={login_screen}
            alt="none"
            className="absolute top-[54%] right-[-10%] translate-y-[-50%] scale-[0.8]"
          />
        </div>
      </div>
    </div>
  );
}