# T20_pointsconfig = {
#         'total_runs': 1,
#         'run_6': 2,
#         'run_4': 1,
#         '>=30' : 4,
#         '>=50': 8,
#         '>=100': 16,
#         'duck': -2,
#         '<50SR': -6,
#         '<60SR': -4,
#         '<=70': -2 ,
#         '>=130SR': 2,
#         '>150SR': 4,
#         '>170SR': 6,
#         'total_wickets': 25,
#         'lbw/bowled_bonus': 8,
#         '>=3W': 4,
#         '>=4W': 8,
#         '>=5W': 16,
#         'maiden_overs': 12,
#         '<5E': 6,
#         '<6E': 4,
#         '<=7E': 2 ,
#         '>=10E': -2,
#         '>11E': -4,
#         '>12E': -6,
#         'total_catches': 8,
#         '>=3C': 4 ,
#         'stumping_bonus': 12,
#         'run_out_bonus_direct': 12,
#         'run_out_bonus_indirect': 6
#     }
T20_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 4,
        '>=50': 8,
        '>=100': 16,
        'duck': -2,
        'S1': -6,
        'S2': -4,
        'S3': -2 ,
        'S4': 2,
        'S5': 4,
        'S6': 6,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 4,
        'W2': 8,
        'W3': 16,
        'maiden_overs': 12,
        'E1': 6,
        'E2': 4,
        'E3': 2 ,
        'E4': -2,
        'E5': -4,
        'E6': -6,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

ODI_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 0,
        '>=50': 4,
        '>=100': 8,
        'duck': -2,
        'S1': -6,
        'S2': -4,
        'S3': -2 ,
        'S4': 2,
        'S5': 4,
        'S6': 6,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 4,
        'W2': 8,
        'W3': 0,
        'maiden_overs': 12,
        'E1': 6,
        'E2': 4,
        'E3': 2 ,
        'E4': -2,
        'E5': -4,
        'E6': -6,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

test_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 0,
        '>=50': 4,
        '>=100': 8,
        'duck': -4,
        'S1': -0,
        'S2': -0,
        'S3': -0,
        'S4': 0,
        'S5': 0,
        'S6': 0,
        'total_wickets': 16,
        'lbw/bowled_bonus': 8,
        'W1': 4,
        'W2': 8,
        'W3': 0,
        'maiden_overs': 0,
        'E1': 0,
        'E2': 0,
        'E3': 0 ,
        'E4': -0,
        'E5': -0,
        'E6': -0,
        'total_catches': 8,
        'C1': 0 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

T10_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 8,
        '>=50': 16,
        '>=100': 0,
        'duck': -2,
        'S1': -6,
        'S2': -4,
        'S3': -2 ,
        'S4': 2,
        'S5': 4,
        'S6': 6,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 8,
        'W2': 16,
        'W3': 0,
        'maiden_overs': 16,
        'E1': 6,
        'E2': 4,
        'E3': 2 ,
        'E4': -2,
        'E5': -4,
        'E6': -6,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

Sixty_points_config = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 8,
        '>=50': 16,
        '>=100': 0,
        'duck': -2,
        'S1': -6,
        'S2': -4,
        'S3': -2 ,
        'S4': 2,
        'S5': 4,
        'S6': 6,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 8,
        'W2': 16,
        'W3': 0,
        'maiden_overs': 16,
        'E1': 6,
        'E2': 4,
        'E3': 2 ,
        'E4': -2,
        'E5': -4,
        'E6': -6,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

The_Hundred_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 5,
        '>=50': 10,
        '>=100': 20,
        'duck': -2,
        'S1': -0,
        'S2': -0,
        'S3': -0 ,
        'S4': 0,
        'S5': 0,
        'S6': 0,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 3,
        'W2': 4,
        'W3': 5,
        'W4' : 10,
        'maiden_overs': 0,
        'E1': 0,
        'E2': 0,
        'E3': 0 ,
        'E4': -0,
        'E5': -0,
        'E6': -0,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

other_T20_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 5,
        '>=50': 10,
        '>=100': 20,
        'duck': -2,
        'S1': -0,
        'S2': -0,
        'S3': -0 ,
        'S4': 0,
        'S5': 0,
        'S6': 0,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 3,
        'W2': 4,
        'W3': 5,
        'maiden_overs': 0,
        'E1': 0,
        'E2': 0,
        'E3': 0 ,
        'E4': -0,
        'E5': -0,
        'E6': -0,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

other_OD_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 5,
        '>=50': 10,
        '>=100': 20,
        'duck': -2,
        'S1': -0,
        'S2': -0,
        'S3': -0 ,
        'S4': 0,
        'S5': 0,
        'S6': 0,
        'total_wickets': 25,
        'lbw/bowled_bonus': 8,
        'W1': 3,
        'W2': 4,
        'W3': 5,
        'maiden_overs': 0,
        'E1': 0,
        'E2': 0,
        'E3': 0 ,
        'E4': -0,
        'E5': -0,
        'E6': -0,
        'total_catches': 8,
        'C1': 4 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }

other_test_pointsconfig = {
        'total_runs': 1,
        'run_6': 2,
        'run_4': 1,
        '>=30' : 0,
        '>=50': 4,
        '>=100': 8,
        'duck': -4,
        'S1': -0,
        'S2': -0,
        'S3': -0 ,
        'S4': 0,
        'S5': 0,
        'S6': 0,
        'total_wickets': 16,
        'lbw/bowled_bonus': 8,
        'W1': 4,
        'W2': 8,
        'W3': 0,
        'maiden_overs': 0,
        'E1': 0,
        'E2': 0,
        'E3': 0 ,
        'E4': -0,
        'E5': -0,
        'E6': -0,
        'total_catches': 8,
        'C1': 0 ,
        'stumping_bonus': 12,
        'run_out_bonus_direct': 12,
        'run_out_bonus_indirect': 6
    }